sudo: required
services:
  - docker

before_install:
  - docker build -t kiry4/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kiry4/react-test npm test -- --coverage

after_success:
  - docker build -t kiry4/multi-client ./client
  - docker build -t kiry4/multi-nginx ./nginx
  - docker build -t kiry4/multi-server ./server
  - docker build -t kiry4/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "DOCKER_ID" --password-stdin
  # Take this images and push them to docker hub
  - docker push kiry4/multi-client
  - docker push kiry4/multi-nginx
  - docker push kiry4/multi-server
  - docker push kiry4/multi-worker